apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
   name: app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: app-deployment
    kind: Deployment
  minReplicas: 1
  maxReplicas: 15
  targetCPUUtilizationPercentage: 25